### ISSUE TITLE
IDEA 2020.3.4 Incompatible version

### ISSUE THREAD

**Issue by hczs** [xBlackCat/ice-framework-idea-plugin#6]
When i installed this plugin and built my project an error occurred.
When I disable this plugin, it's OK
Here are the details of the error

`Internal error (java.lang.UnsupportedClassVersionError): org/xblackcat/frozenidea/jps/ModelSerializerExtension has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
java.lang.UnsupportedClassVersionError: org/xblackcat/frozenidea/jps/ModelSerializerExtension has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.intellij.util.containers.ContainerUtilRt.copy(ContainerUtilRt.java:113)
	at com.intellij.util.containers.ContainerUtil.newArrayList(ContainerUtil.java:205)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl$SingleClassLoaderPluginManager.loadExtensions(JpsServiceManagerImpl.java:113)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.loadExtensions(JpsServiceManagerImpl.java:105)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.getExtensions(JpsServiceManagerImpl.java:58)
	at org.jetbrains.jps.model.serialization.JpsModelSerializerExtension.getExtensions(JpsModelSerializerExtension.java:47)
	at org.jetbrains.jps.model.serialization.library.JpsLibraryTableSerializer.getLibraryPropertiesSerializer(JpsLibraryTableSerializer.java:110)
	at org.jetbrains.jps.model.serialization.library.JpsLibraryTableSerializer.loadLibrary(JpsLibraryTableSerializer.java:51)
	at org.jetbrains.jps.model.serialization.library.JpsLibraryTableSerializer.loadLibrary(JpsLibraryTableSerializer.java:46)
	at org.jetbrains.jps.model.serialization.library.JpsLibraryTableSerializer.loadLibraries(JpsLibraryTableSerializer.java:41)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader$GlobalLibrariesSerializer.loadExtension(JpsGlobalLoader.java:113)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader$GlobalLibrariesSerializer.loadExtension(JpsGlobalLoader.java:106)
	at org.jetbrains.jps.model.serialization.JpsLoaderBase.loadComponents(JpsLoaderBase.java:46)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalComponents(JpsGlobalLoader.java:80)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.load(JpsGlobalLoader.java:70)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalSettings(JpsGlobalLoader.java:43)
	at org.jetbrains.jps.model.serialization.impl.JpsSerializationManagerImpl.loadModel(JpsSerializationManagerImpl.java:21)
	at org.jetbrains.jps.cmdline.JpsModelLoaderImpl.loadModel(JpsModelLoaderImpl.java:34)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:64)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:279)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:132)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

`

**Comment by xBlackCat** [comment]
Plugin was migrated to Java 11 codebase. Could you update JDK of your project to Java 11 version? It should help to run source builder.

**Comment by hczs** [comment]
> Plugin was migrated to Java 11 codebase. Could you update JDK of your project to Java 11 version? It should help to run source builder.

Ok, solved, thank you~
