### ISSUE TITLE
java.lang.ClassCastException: class com.intellij.lang.javascript.psi.impl.JSFileImpl cannot be cast to class org.xblackcat.frozenidea.psi.SliceFile (com.intellij.lang.javascript.psi.impl.JSFileImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @14f41e22; org.xblackcat.frozenidea.psi.SliceFile is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @258c0f2c)

### ISSUE THREAD

**Issue by eegiazarov** [xBlackCat/ice-framework-idea-plugin#8]
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-46-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 20
Non-Bundled Plugins:
    org.jetbrains.plugins.go-template (222.3345.108)
    com.intellij.ideolog (203.0.30.0)
    String Manipulation (9.5.1)
    FrozenIdea (0.0.6.0)
    com.intellij.kubernetes (222.3345.108)
    intellij.prettierJS (222.3345.108)

Kotlin: 222-1.7.10-release-334-IJ3345.118
Current Desktop: ubuntu:GNOME

```
java.lang.ClassCastException: class com.intellij.lang.javascript.psi.impl.JSFileImpl cannot be cast to class org.xblackcat.frozenidea.psi.SliceFile (com.intellij.lang.javascript.psi.impl.JSFileImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @14f41e22; org.xblackcat.frozenidea.psi.SliceFile is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @258c0f2c)
	at org.xblackcat.frozenidea.util.SliceUtil.findNamedItems(SliceUtil.java:96)
	at org.xblackcat.frozenidea.code.SliceGotoSymbolContributor.getNames(SliceGotoSymbolContributor.java:21)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:132)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:83)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:77)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$0(JobLauncherImpl.java:52)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:52)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

**Comment by xBlackCat** [comment]
Sorry, I have no oportunies to support IJ plugins anymore.
